### ISSUE TITLE
Bitcoin address

### ISSUE THREAD

**Issue by andreaadorno** [fl0wo/TradingFX#1]
Hi,

Thank you for developing this application. It helped me make about 1 BTC by trading it against USDC.

I would like to send you a little gift to show my appreciation for this project. Would you mind sharing your BTC wallet address?

Thank you again,
Andrea

**Comment by abiwendesen** [comment]
3KCHkaMRsteyardJ6C4tzhqszQAmGaaJdu

**Comment by andreaadorno** [comment]
@fl0wo What is your bitcoin address so I can send you the gift?

**Comment by fl0wo** [comment]
ahahah thanks @andreaadorno no there’s no need to gift anything, peace.

Anyway thats my wallet bc1qm50vw9uh7k4dghewqygyye2cqavjgyrk9y6lj4

**Comment by demiralhami06** [comment]
1J9UDcdha5qeuMjsE35ywYhVZTZDfKFrJ4

**Comment by demiralhami06** [comment]
bc1pr79uw6jt5urtlt96r6vg0qe9lq505j4yyzpq00fqtpg7q2m56wjqk2w7a5

**Comment by demiralhami06** [comment]
3H9ZLwaQDTkEEffGrz5daj9EsY7CbW9EBR
